server:
  port: 4295

towerhawk:
  monitor:
    checkDefinitionDir: config/
  checkRunnerThreadPool:
    corePoolSize: 10
    maxPoolSize: 10
  appRunnerThreadPool:
    corePoolSize: 10
    maxPoolSize: 10

