server:
  port: 4295

towerhawk:
  monitor:
    checkDefinitionDir: config/
  checkRunnerThreadPool:
    corePoolSize: 1
    maxPoolSize: 1
  appRunnerThreadPool:
    corePoolSize: 1
    maxPoolSize: 1

