server:
  port: 4295

towerhawk:
  monitor:
    checkDefinitionDir: config/
    checkRunDefaultFields:
      - status
      - message
  checkRunnerThreadPool:
    corePoolSize: 1
    maxPoolSize: 1
  appRunnerThreadPool:
    corePoolSize: 1
    maxPoolSize: 1

