apps:
  zookeeper:
    alias: zk
    cacheMs: 10000
    defaultCacheMs: 1000
    timeoutMs: 20000
    priority: 0
    tags:
      - java
    checks:
      port2181:
        type: portResponse
        alias: zkPort
        priority: 2
        timeoutMs: 2000
        host: localhost
        port: 2181
        threshold:
          warning:
            upper: 1000
          critical:
            upper: 3000
          addContext: true
        send: ruok
        response:
          regex: imok
          addContext: true
          setMessage: true
        activeCheck:
          type: daily
          startTime: 09:00:59.234567891
          endTime: 17:00:03.345678901
          timeFormat: HH:mm:ss.SSSSSSSSS
        unknownIsCritical: false
        tags:
          - tcp
      zkProcess:
        type: shell
        alias: zkProcess
        priority: 1
        timeoutMs: 3000
        cmd: 'echo $SOME_VAR - $OTHER_VAR'
        env:
          SOME_VAR: someValue
          OTHER_VAR: otherValue
        tags:
          - ps
        recentChecks:
          sizeLimit: 20
#      heapSize:
#        type: javaheap
#        port: 12181
#        threshold:
#          type: nagios
#          warning: 80
#          critical: 90
#          addContext: true
#          setMessage: true
#          precision: 0
  kafka:
    alias: messaging
    cacheMs: 10000
    defaultCacheMs: 1000
    timeoutMs: 20000
    priority: 2
    active:
      type: disabled
    tags:
      - java
    checks:
      port9092:
        type: port
        alias: kafkaPort
        priority: 2
        timeoutMs: 1000
        port: 9092
        threshold:
          warning:
            upper: 200
          critical:
            upper: 500
          addContext: true
          setMessage: true
        tags:
          - tcp
  os:
    checks:
      system:
        type: system
        loadAverage:
          threshold:
            type: nagios
            warning: ~:0.9
            critical: ~:1
            setMessage: true
  test:
    timeoutMs: 2000
    checks:
      crit:
        type: critical
      warn:
        type: warning
      succeeded:
        type: succeeded
      timeout:
        type: timeout
        unknownIsCritical: false
