apps:
  zookeeper:
    alias: zk
    cacheMs: 1000
    timeoutMs: 20000
    priority: 0
    tags:
      - java
    checks:
      port2181:
        type: .type.PortCheck
        alias: zkPort
        priority: 2
        timeoutMs: 2000
        host: 192.168.1.202
        port: 2181
        send: ruok
        expectRegex: imok
        includeOutputInContext: true
        activeCheck:
          type: .ScheduleActive
          startHour: 9
          endHour: 9
        matchIsCritical: false
        tags:
          - tcp
      zkProcess:
        type: .type.ShellCheck
        alias: zkProcess
        priority: 1
        timeoutMs: 3000
        cmd: 'echo $SOME_VAR'
        env:
          SOME_VAR: someValue
          OTHER_VAR: otherValue
        tags:
          - ps
        recentChecks:
          sizeLimit: 20
  kafka:
    alias: messaging
    cacheMs: 120000
    timeoutMs: 20000
    priority: 0
    tags:
      - java
    checks:
      port9092:
        type: .type.PortCheck
        alias: kafkaPort
        priority: 2
        timeoutMs: 1000
        port: 9092
        tags:
          - tcp
